### PR TITLE
Support mainland China region

### PR DESCRIPTION
**Pull request by me0726**
Hello, I have added a prayer record function on mainland China.

Here are the modification points:

### When gamebiz == 'hk4e_ cn'
- **im-endpoint** is modified to 'https://api-takumi.mihoyo.com'
- **wish-endpoint** is modified to 'https://hk4e-api.mihoyo.com'
-  mainland China  Uid is start with '1'.

**NOTE:
This requires request provider  *authkey* and *gime_ biz*.**
But my front-end technology is not good. :)

### CODE REVIEW

**Comment by Ishou** [comment]
Hi! I did not know that Mainland China required a different endpoint 😭 
Thanks a lot for your work!

~~Since there is a distinction with the UIDs starting by "1" I'd prefer using this information to know which endpoint to use.
This way the front-end would not need to send the game_biz and the back-end would have everything it needs as it is 😄 You can access the UID with user.getMihoyoUid()
What do you think about this?~~

Also my Region enum is badly named, I need to rework this part to make it clearer because right now it's just America 6 | Europe 7 | Asia (1,8,9..) (regrouping all regions)
It means that "CHINA" should not be in this enum but in a new one I'd need to create, for the moment you can just remove it from the enum

**EDIT:** I just saw that the endpoint we use to fetch the UID also requires a change so what I said does not work

**Comment by Ishou** [comment]
I just did the changes for the front-end part so everything's ready 😄 I just need you to remove the "CHINA" in Region enum otherwise it will cause issues in our global statistics

I'll create two separate enums later on

**Comment by me0726** [comment]
I'm done. :)

**Review by Ishou — APPROVED** [review]

**Comment by Ishou** [comment]
Thanks a lot 😄 I'm looking forward to seeing people from mailand China using the website 😃 
I'll deploy this as soon as possible

**Comment by Ishou** [comment]
Could you try importing from your mainland China account? 😄 Should be working now

**Comment by me0726** [comment]
It works well !！

However, there is a bad message that Chinese mainland can not access Google, Facebook and Discord. So the oauth2 login of this website is not available to us. Is it possible to provide a mailbox login mode?

**Comment by Ishou** [comment]
A mail & password login brings difficulties we would like to avoid 😭 

Do you know any oauth2 providers that would be commonly used and accessible from mainland China?

I already checked WeChat but it's kinda complicated to use... Maybe Weibo or QQ?

**Comment by me0726** [comment]
If you can provide QQ or WeChat login, that's really good.  😃

**Comment by Ishou** [comment]
I'm having trouble creating a QQ account, do you think you could create one for me and explain me how to change the password afterwards?

**Comment by me0726** [comment]
What difficulties do you have at present? QQ account registration needs a mobile phone number, my mobile phone number has been bound with a QQ.

**Comment by Ishou** [comment]
Well it refuses my France phone number, I was able to create a WeChat account but WeChat asks for 99$ annually to use the oauth

We might just add a login / password authentication... it will be simplier but we also need to do something to send password reset mails etc

**Comment by me0726** [comment]
That seems to be the only way.  🤣

**Comment by Ishou** [comment]
Would Baidu oauth be fine? I think I can manage it

**Comment by me0726** [comment]
Baidu is not as widely used as QQ. When oauth2 logs in, you may need to enter Baidu's username and password,but at least it can be used😂。

**Comment by Ishou** [comment]
Hi! We added Baidu as a provider 😄 
image

We're checking if we could add QQ but it's difficult

**Comment by me0726** [comment]
nice！！👍

**Pull request merged**
